const assert = require('assert');

var noDivZero = (dividend, divisor) => {
  try {
    assert(divisor !== 0, 'DivisionByZeroException')
    return dividend / divisor
  } catch(e) {
    return e.message
  }
}

noDivZero(10, 0); // DivisionByZeroException